config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :word_files,only: [:index,:new] do
    collection do
      get :docx
      post :docx_post, format: 'docx'
    end
  end
  root "word_files#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/word_files_controller.rb
class WordFilesController < ApplicationController

    def index 

    end 

    def docx

    end

    def docx_post
      delete_file
      file = File.new("/#{Rails.root}/public/snippet.docx","w")
      my_html = "<html><head></head><body>"
      my_html += "<h2>#{params[:nom]}</h2>" if params[:nom]
      if params[:logo]
        file_data = params[:logo].tempfile
        file_path = File.join("public", params[:logo].original_filename)
        FileUtils.cp file_data.path, file_path
        my_html += "<p style='text-align: left;'><img src=\'http://localhost:3000/#{params[:logo].original_filename}' style=\'width: 250px; height: 100px\'></p>"
      end
      if params[:column]
        my_html += "<table style='margin-top: 30px;'><thead><tr>"
        params[:column].each do |th|
          my_html += "<td>#{th}</td>"
        end 
        my_html += "</thead><tbody>"
        params[:row].each do |k,row|
          my_html += "<tr>"
          row.each do |row_text|
            my_html +="<td>#{row_text}</td>"
          end
          my_html += "</tr>"
        end    
        my_html += "</tbody></table>"  
        my_html += "</body></html>"
      end
      # document = Htmltoword::Document.create my_html,"snippet.docx"
      file = Htmltoword::Document.create_and_save(my_html, "/#{Rails.root}/public/snippet.docx")
      File.delete(file_path) if params[:logo]
      send_file("#{Rails.root}/public/snippet.docx" ,
          :type => 'application/pdf/docx/html/htm/doc',
          :disposition => 'attachment')  
    end
    
    private

    def delete_file
      if File.exist?("#{Rails.root}/public/snippet.docx")
        File.delete("#{Rails.root}/public/snippet.docx")
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/word_files_helper.rb
module WordFilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CreateDocx</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </head>

  <body>
    <main class="container">
      <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/word_files/_add_input.html.erb
<% if defined?(child_index) %>
    <%= text_field_tag "#{name}[#{child_index}][]" ,'', class: "form-control border-0" ,data:{index: child_index}%>
<% else %>
    <%= text_field_tag "#{name}[]" ,'', class: "form-control border-0"%>
<% end %>

app/views/word_files/_add_row.html.erb
<tr class="row-div" data-index="<%=child_index%>">
    <% total.to_i.times do |index| %>
        <%= render "with_tr" , name:name, child_index: child_index.to_i %>
    <% end %>
</tr>

app/views/word_files/_with_tr.html.erb
<th scope="col">
<% if defined?(child_index) %>
    <%= render "add_input" , name: name, child_index: child_index%>
<% else %>
    <%= render "add_input" , name: name %>
<% end %>
</th>

app/views/word_files/docx.html.erb
<div class="row text-">
    <div class="col-md-12 text-end mb-3">
        <button type="button" class="btn btn-success" style="margin-right: 5px;" id="add-column">Add Columns</a>
        <button type="button" class="btn btn-success">Add Remove Columns</button>
        <button type="submit" class="btn btn-success" form="formsave">Download</button>
    </div>
    <div class="table-responsive">
        <%= form_tag docx_post_word_files_url, multipart: true ,id:"formsave" do %>
            <div class="col-6">
                <div class="form-group">
                    <label for="exampleInputEmail1">Nom</label>
                    <input type="text" class="form-control" name="nom" id="exampleInputEmail1">
                </div>
                <div class="form-group mt-3 mb-3">
                    <label for="exampleFormControlFile1">Logo Photo</label>
                    <input type="file" name="logo" class="form-control-file" id="exampleFormControlFile1">
                </div>
            </div>

            <table class="table table-bordered">
                <thead>
                    <tr id="columns-div">
                        <% 3.times do |index| %>
                            <%= render "with_tr" , name: "column"%>
                        <% end %>
                    </tr>
                </thead>
                <tbody>
                    <tr class="row-div" data-index="0">
                        <% 3.times do |index| %>
                            <%= render "with_tr" , name: "row", child_index: 0%>
                        <% end %>
                    </tr>
                </tbody>
            </table>
        <% end %>
    </div>
    <div class="col-md-12 text-end mt-3">
        <button type="button" class="btn btn-success" id="add-row">Add Row</button>
        <button type="button" class="btn btn-success">Add Remove Row</button>
    </div>

</div>

 <script type="text/javascript">
    $('#add-column').click(function() {
        // row last index we have
        rewards_tier_index = $(".row-div").last().data("index") + 1;
        $.ajax({
            url: "<%= new_word_file_url %>",
            // type: "GET",
            data: { type: "add-column",index: rewards_tier_index ,total_row:  $(".row-div").last().find("input").length}
        })
    });
     $('#add-row').click(function() {
        rewards_tier_index = $(".row-div").last().data("index") + 1;
        $.ajax({
            url: "<%= new_word_file_url %>",
            // type: "GET",
            data: { type: "add-row" , index: rewards_tier_index ,total_row:  $(".row-div").last().find("input").length}
        })
    });
</script>

app/views/word_files/index.html.erb
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card mb-4 shadow-sm">
            <div class="card-body">
                <a href="<%= docx_word_files_url %>">
                    <h4 class="my-0 fw-normal">Docx</h4>
                </a>
            </div>
        </div>
    </div>
</div>

app/views/word_files/new.js.erb
<% if params[:type] == "add-column" %>
    $("#columns-div").append('<%= escape_javascript("#{render 'with_tr', name: "column"}").html_safe %>');
    <% params[:index].to_i.times do |index| %>
    $(".row-div[data-index='<%=index%>']").append('<%= escape_javascript("#{render 'with_tr', name: "row" , child_index: index }").html_safe%>'); 
    <% end %>
<% end %>
<% if params[:type] == "add-row" %>
    $("tbody").append('<%= escape_javascript("#{render 'add_row', name: "row" , child_index: params[:index],total: params[:total_row]}").html_safe %>');
<% end %>